spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xiaoshuo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: xjz
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml  #映射文件
  type-aliases-package: com.example.demo.entity #实体文件的目录